output:	bubbleSort.o insertionSort.o main.o menu.o mergeSort.o quickSort.o selectionSort.o shuf.o shellSort.o radixSort.o quickInsertion2.o
	g++ -std=c++11 -Wall bubbleSort.o insertionSort.o main.o menu.o mergeSort.o quickSort.o selectionSort.o shuf.o shellSort.o radixSort.o quickInsertion2.o -o consulta -lm -I include/
	-rm *.o
main.o:
		g++ -std=c++11 -o main.o -c main.cpp -Wall 
bubbleSort.o:
	g++ -o bubbleSort.o -c bubbleSort.cpp -Wall -std=c++11
insertionSort.o:
	g++ -o insertionSort.o -c insertionSort.cpp -Wall -std=c++11
menu.o:
	g++ -o menu.o -c menu.cpp -Wall -std=c++11
mergeSort.o:
	g++ -o mergeSort.o -c mergeSort.cpp -Wall -std=c++11
quickSort.o:
	g++ -o quickSort.o -c quickSort.cpp -Wall -std=c++11
selectionSort.o:
	g++ -o selectionSort.o -c selectionSort.cpp -Wall -std=c++11
shuf.o:
	g++ -o shuf.o -c shuf.cpp -Wall -std=c++11
radixSort.o:
	g++ -o radixSort.o -c radixSort.cpp -Wall -std=c++11
shellSort.o:
	g++ -o shellSort.o -c shellSort.cpp -Wall -std=c++11
quickInsertion2.o:
	g++ -o quickInsertion2.o -c quickInsertion2.cpp -Wall -std=c++11
